# Understanding Numpy: A Simple Introduction
Numpy, short for Numerical Python, is a powerful Python library that enables efficient and convenient array manipulation and mathematical operations. It forms the foundation for many scientific and data-related tasks. In this article, we'll provide a straightforward explanation of Numpy concepts and how to use them.

## Importing Numpy
Before diving into Numpy's capabilities, we need to import it. Conventionally, we import Numpy with the alias np, making it easier to reference its functions:

In [1]:
import numpy as np

## Creating Arrays
Basic Array Creation
NumPy provides several functions to create arrays:

- np.zeros(10): Creates an array of 10 zeros
- np.ones(10): Creates an array of 10 ones
- np.full(10, 2.5): Creates an array of 10 elements, all with value 2.5

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

## From Python Lists
Convert a Python list to a NumPy array:

In [6]:
[1, 2, 3, 5, 7, 12]
np.array([1, 2, 3, 5, 7, 12])
a=np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

## Accessing and Modifying Elements
Access elements using zero-based indexing:

In [10]:
a[2]  # Returns the third element (3)
a[2] = 10  # Changes the third element (3) to 10, ie (3) becomes (10)
a

array([ 1,  2, 10,  5,  7, 12])

## Range-Based Arrays
Create arrays with sequential values:

In [11]:
np.arange(10) ##Creates array with values 0 through 9
np.arange(3, 10) ##Creates array with values 3 through 9
np.linspace(0, 1, 11) ##Creates 11 evenly spaced values from 0 to 1 inclusive

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])